[build]
  command = "npm run netlify-build"
  publish = "out"

[build.environment]
  NETLIFY_USE_YARN = "false"
  NODE_VERSION = "18"
  PORT = "3000"
  # Skip Next.js plugin as we're using static export
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# No plugins for static export

# Development server configuration
[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  framework = "#custom"
  # Enable websocket connection for hot module replacement
  autoLaunch = true
  
# Functions configuration for serverless deployment
[functions]
  # Keep function execution time short for better performance
  node_bundler = "esbuild"
  external_node_modules = ["@next/swc-linux-x64-gnu", "@next/swc-linux-x64-musl"]

# Health checks configuration
[[redirects]]
  from = "/.netlify/health"
  to = "/health"
  status = 200
  force = true

[[redirects]]
  from = "/health-check"
  to = "/health"
  status = 200
  force = true

# Handle WebSocket connections for hot module replacement
[[redirects]]
  from = "/_next/webpack-hmr"
  status = 200
  force = true
  conditions = {Role = ["admin"]}
  headers = {X-From = "Netlify"}
  
# Ensure nested page routes work correctly - high priority redirects
[[redirects]]
  from = "/about/people"
  to = "/about/people/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/about/people/"
  to = "/about/people/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/about/ethos"
  to = "/about/ethos.html"
  status = 200
  force = true

[[redirects]]
  from = "/about/ethos/"
  to = "/about/ethos.html"
  status = 200
  force = true

[[redirects]]
  from = "/community/events"
  to = "/community/events.html"
  status = 200
  force = true

[[redirects]]
  from = "/community/events/"
  to = "/community/events.html"
  status = 200
  force = true

[[redirects]]
  from = "/contact/form"
  to = "/contact/form.html"
  status = 200
  force = true

[[redirects]]
  from = "/contact/form/"
  to = "/contact/form.html"
  status = 200
  force = true

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200
  force = true

[[redirects]]
  from = "/contact/"
  to = "/contact.html"
  status = 200
  force = true

[[redirects]]
  from = "/careers"
  to = "/careers.html"
  status = 200
  force = true

[[redirects]]
  from = "/careers/"
  to = "/careers.html"
  status = 200
  force = true

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy-policy.html"
  status = 200
  force = true

[[redirects]]
  from = "/privacy-policy/"
  to = "/privacy-policy.html"
  status = 200
  force = true

# Fallback for client-side routing (only for valid paths)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Handle 404 errors properly - lowest priority
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404